albertomota_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^blog/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
]

blog/urls.py
from django.conf.urls import include, url

from . import views
app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexPostView.as_view(), name='index_posts'),
    url(r'^register/', views.UserFormView.as_view(), name='register'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^$', views.IndexPostView.as_view(), name='index_posts'),

    url(r'^(?P<pk>[0-9]+)/$', views.ReadPostView.as_view(), name='read_post'),
    url(r'^(?P<pk>[0-9]+)/update_post/$', views.UpdatePostView.as_view(), name='update_post'),
    url(r'^createPost/$', views.PostCreateView.as_view(), name='create_post'),
    url(r'^(?P<pk>[0-9]+)/delete_post/$', views.PostDeleteView.as_view(), name='delete_post'),
    url(r'^accounts/', include('allauth.urls')),
]

blog/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.
class Post(models.Model):
    text              = models.TextField(blank=False)
    title             = models.CharField(max_length=200,default="No Title")
    publication_date  = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User,null= True)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User

from blog.models import Post

class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']



class PostForm(forms.ModelForm):

    # confirm_title = forms.CharField(
    #     label="confirm_title",
    #     required=True,
    # )

    class Meta:
        model = Post
        fields = '__all__'
        exclude = ['user'] 

    def __init__(self, *args, **kwargs):

        # if kwargs.get('instance'):
        #     title = kwargs['instance'].title
        #     kwargs.setdefault('initial', {})['confirm_title'] = title

        return super(PostForm, self).__init__(*args, **kwargs)

    def clean_title(self):
        title = self.cleaned_data['title']
        if not title:
           raise ValidationError("Title cannot be blank")

        if len(title) <5:
           raise ValidationError("Title is too short.")

        if len(title) >100:
           raise ValidationError("Title is too long.")

        return title

    def clean_text(self):
        text = self.cleaned_data['text']
        if not text:
           raise ValidationError("Post-text cannot be blank")

        if len(text) <140:
           raise ValidationError("Post-text is too short.")
           
        if len(text) >10000:
           raise ValidationError("Post-text is too long.")
        return text

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# Create your views here.
from django.views import generic
from .models import Post
from django.urls import reverse, reverse_lazy
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm
from django.contrib.auth import logout
from django.contrib.auth.models import User
import forms
import logging

def logout_view(request):
    logout(request)
    return redirect('blog:index_posts')

class UserFormView(View):
    form_class    = UserForm
    template_name = "blog/registration_form.html"

    def get(self,request):
        form = self.form_class(None)
        return render(request, self.template_name,{'form':form})

    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit = False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.username = username
            user.save()

            user = authenticate(username =username, password = password )

            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect("blog:index_posts")

        return render(request, self.template_name,{'form':form})


class IndexPostView(generic.ListView):
    template_name = 'blog/index_posts.html'
    context_object_name = 'post_list'
    

    def get_queryset(self):
        a=self.request.GET.get('q', '')
        #return Post.objects.all()
        return Post.objects.filter(text__icontains=a) |  Post.objects.filter(title__icontains=a)

class ReadPostView(generic.DetailView):
    model = Post
    template_name = 'blog/readPost.html'


class UpdatePostView(generic.edit.UpdateView):
    model = Post
    #fields = ['title','text']
    template_name_suffix = '_update_form'
    form_class = forms.PostForm

    def get_success_url(self):        
        return reverse('blog:index_posts')

class PostCreateView(generic.edit.CreateView):
    model = Post
    #fields = ['title','text','publication_date']
    form_class = forms.PostForm

    def get_success_url(self):
        return reverse('blog:index_posts')

    def form_valid(self, form):
        obj = form.save(commit=False)
        if isinstance(self.request.user,User):
            obj.user = self.request.user
            obj.save()        
        return super(PostCreateView, self).form_valid(form)

class PostDeleteView(generic.edit.DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index_posts')

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block head_title %}AMRblog{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'blog/css/bootstrap-theme.min.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script type="text/javascript" src="{% static 'blog/js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'blog/js/npm.js' %}"></script>

    </head>
    <body>

    	<nav class="navbar navbar-default">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <a class="navbar-brand" href="/blog/"> AMR Blog</a>
              <ul class="nav navbar-nav">
                
                    {% if user.is_authenticated %}
                        <li class="nav-item ">
                            <p>Hola {{ user.username }} !!!</p> 
                        </li>
                        <li class="nav-item ">
                            <a href="/blog/logout">logout</a>      
                        </li>
                    {% else %}
                        <li class="nav-item ">
                            <a href="register">Register</a>     
                        </li>
                    {% endif %} 
                </li>
              </ul>
		    </div>
            
		  </div><!-- /.container-fluid -->
		</nav>

        
        
        <div class="container">
        	{% block content %}
        </div>

        {% endblock %}
    </body>
</html>

blog/templates/blog/index_posts.html
{% extends 'blog/base.html' %}

{% block content %}

	<div class="row">
  	<div class="col-xs-6 col-md-4">
  	</div>
  	<div class="col-xs-6 col-md-4">
  		<h4 align="center">Posts</h4>
  	</div>
  	<div class="col-xs-6 col-md-4">
  	</div>
	</div>

	<form action="/blog/" method="GET">
		<div class="form-group row">
			<label for="example-text-input" class="col-xs-1 col-form-label">Filter</label>
			<div class="col-xs-6">
				<input class="form-control" type="text" value="" name="q"> 
			</div>
			<div class="col-xs-3">
				<button type="submit" class="btn btn-primary">Filter</button>
			</div>
			
		</div>
	</form>

	{% if post_list %}
	   <table class="table">
	   	<tr>
	   		<th>Title</th>
	   		<th></th>
	   	</tr>
	    {% for post in post_list %}
	        <tr>
	        	<td>
	        		<a href="{% url 'blog:read_post' post.id %}">{{ post.title }}</a>
	        	</td>
	        	<td>
	        		<a href="{% url 'blog:delete_post' post.id %}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
	        		<a href="{% url 'blog:update_post' post.id %}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a>
	        	</td>
	        </tr>
	    {% endfor %}
	    </table>
	{% else %}
	    <p>No polls are available.</p>
	{% endif %}

	<div class="row">
  	<div class="col-xs-6 col-md-4">
  	</div>
  	<div class="col-xs-6 col-md-4">
  		<div align = "center">
  			<a class="btn btn-default" href="{% url 'blog:create_post' %}" role="button">New Post</a>
  		</div>
  		
  	</div>
  	<div class="col-xs-6 col-md-4">
  	</div>
	</div>
	

{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}
	<form action="" method="post">{% csrf_token %}
	    <p>Are you sure you want to delete "{{ object }}"?</p>
	    <input type="submit" value="Confirm" />
	</form>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block content %}
	<h2>Create</h2>
	<form action="" method="post">{% csrf_token %}
		<div class="form-group">

	    	 {{ form.as_p }}
			
	    	<input type="submit" class="btn" value="Create" />
	    </div>
	</form>
{% endblock %}	

blog/templates/blog/post_update_form.html
{% extends 'blog/base.html' %}

{% block content %}
	<h2>Update</h2>
	<form action="" method="post">{% csrf_token %}
	    {{ form.as_p }}
	    <input type="submit" value="Update" />
	</form>
{% endblock %}

blog/templates/blog/readPost.html
{% extends 'blog/base.html' %}

{% block content %}
	
	<div class="jumbotron">
		<h2>{{ post.title }}</h2>
		
		{% if post.user is not None %}
			<h4> {{ post.user.username }}</h4>
		{% else %}
			<h4> Anonymous</h4>
		{% endif %}
		<h6>{{ post.publication_date }}</h6>
		<p>{{ post.text }}</p>
	</div>	
	
{% endblock %}

blog/templates/blog/registration_form.html
{% extends 'blog/base.html' %}

{% block content %}
	<h2>Create</h2>
	<form action="" method="post">{% csrf_token %}
		<div class="form-group">

	    	 {{ form.as_p }}
			
	    	<input type="submit" class="btn" value="Create" />
	    </div>
	</form>
{% endblock %}	